#!/bin/bash

cd /workspace

# upgrade pip
python -m pip install --upgrade pip

# install python dependencies:
pip install -r /workspace/requirements.txt

# install pre-commit hooks to git:
pre-commit install
