[project]
name = "datahub_test_bed"
version = "0.0.1"
description = "GHGA's utility tool for technical validation of Data Hubs and benchmarks"
dependencies = [
]

[project.urls]
Repository = "https://github.com/ghga-de/datahub-test-bed"

[project.scripts]
datahub-test-bed = "datahub_test_bed.__main__:run"
